#! /bin/bash

getGitBranch()
{
   git -C $QA_SRC branch | grep '*' | awk '{print $2}'
   return
}

getVersion()
{
  # get current revision number; this determines whether it is
  # before a change of defaults happened.
  local branch currIdent tag tmp tmp2
  declare -a tmp

  if [ $CONDA_PATH ] ; then
    if tmp=( $(cat ${QA_SRC}/install.log 2> /dev/null) ) ; then
      branch=${tmp[0]#*=}
      currIdent=${tmp[1]#*=}
      test ${#tmp[*]} -gt 2 && tag=${tmp[2]#*=}
    fi
  else
    local f=${QA_SRC}/conda-recipes/qa-dkrz/meta.yaml

    branch=$(getGitBranch)
    currIdent=$(git -C ${QA_SRC} log --pretty=format:'%h' -n 1)

    tag=$( grep 'name:' $f | awk '{print $(NF)}' )
    tmp2=$( grep 'version:' $f | awk '{print $(NF)}' )
    tmp2=${tmp2:1}
    tag2=${tag}-${tmp2:0:$((${#tmp}-1))}
    tmp2=$( grep 'number:' $f | awk '{print $(NF)}' )
    tag=${tag}-${tmp2}
  fi

  if [ $# -eq 0 ] ; then
    echo "QA version:"
    echo "   GitHub: https://github.com/IS-ENES-Data/QA-DKRZ.git"
    echo "   branch: ${branch}"
    echo "   commit-SHA: ${currIdent}"
    echo "   tag: ${tag}"
    exit
  else
    eval ${1}="${branch}-${currIdent},${tag}"
  fi

  return
}

if [ "$1" = "func=getGitBranch" ] ; then
  getGitBranch
else
  getVersion $*
fi

exit 0
