#! /bin/bash

# which for path and alias, even if non-interactive

this_which()
{
  local cm cmd f found i j k last lines
  declare -a cmd f found lines

  # try which
  found=( $( which -a $1 2> /dev/null ) )

  # files which could have aliases
  f[0]=${HOME}/.bashrc

  local saveIFS
  saveIFS="${IFS}"

    for(( i=${#f[*]}-1 ; i > -1 ; --i )) ; do
      # scan for alias. Note such is not effective here
      IFS=$'\r\n'
      lines=( $(grep alias ${f[i]}) )
      lines=( ${lines[*]} $(grep ' \. ' ${f[i]}) )
      lines=( ${lines[*]} $(grep ' source ' ${f[i]}) )
      
      IFS="${saveIFS}"

      unset f[i]
      f=( ${f[*]} )

      for(( k=0 ; k < ${#lines[*]} ; ++k )) ; do
        cmd=( ${lines[k]} )
        test ${cmd[0]:0:1} = '#' && continue

        # is a file executed by source or . ?
        for(( j=0 ; j < ${#cmd[*]} ; ++j )) ; do
           if [ "${cmd[j]}" = '.' -o "${cmd[j]}" = 'source' ] ; then
              j=$((j+1))
              cm=${cmd[j]//\~/${HOME}}
              if [ -f ${cm} ] ; then
                f[${#f[*]}]=${cm}
                continue 2
              fi
           fi
        done

        for(( j=1 ; j < ${#cmd[*]} ; ++j )) ; do
           # search alias
           test ${cmd[0]} != 'alias' && break

           cm=${cmd[j]#*=}
           last=$((${#cm} - 1 ))
           test ${cm:last} = \' -o ${cm:last} = '"' && cm=${cm:0:last}

           if [ ${cm##*/} == ${1} ] ; then
              # found an alias containing the command in question
              test ${cm:0:1} = \' -o ${cm:0:1} = '"' && cm=${cm:1}


              found[${#found[*]}]=${cm}
              break
           fi
        done
      done

      i=${#f[*]}
    done

    for(( k=0 ; k < ${#found[*]}-1 ; ++k )) ; do
      for(( i=k+1 ; i < ${#found[*]} ; ++i )) ; do
        if [ ${found[k]} = ${found[i]} ] ; then
           unset found[k]
           break
        fi
      done
    done

    if [ ${#found[*]} -eq 0 ] ; then
      echo "no such command or alias $1" > /dev/stderr
      return 1
    fi

  echo ${found[*]}
  return 0
}

this_which $*

exit $?

